#!/usr/bin/env python
# coding: utf8


class Error:
    """Represent error values that will be caught by error callbacks
    Warning: If you happen to change the values, make sure they correspond
    to the values of the corresponding C enum
    """
    def __init__(self):
        pass

    (
        DZ_ERROR_NO_ERROR,
        DZ_ERROR_NO_ERROR_ASYNC,
        DZ_ERROR_ERROR_ARG,
        DZ_ERROR_ERROR_STATE,
        DZ_ERROR_NOT_IMPLEMENTED,
        DZ_ERROR_ASYNC_CANCELED,
        DZ_ERROR_NOT_ENOUGH_MEMORY,
        DZ_ERROR_OS_ERROR,
        DZ_ERROR_UNSUPPORTED,
        DZ_ERROR_CLASS_NOT_FOUND,
        DZ_ERROR_JSON_PARSING,
        DZ_ERROR_XML_PARSING,
        DZ_ERROR_PARSING,
        DZ_ERROR_CLASS_INSTANTIATION,
        DZ_ERROR_RUNNABLE_ALREADY_STARTED,
        DZ_ERROR_RUNNABLE_NOT_STARTED,
        DZ_ERROR_CACHE_RESOURCE_OPEN_FAILED,
        DZ_ERROR_FS_FULL,
        DZ_ERROR_FILE_EXISTS,
        DZ_ERROR_IO_ERROR,
    ) = range(0, 20)

    (
        DZ_ERROR_CATEGORY_CONNECT,
        DZ_ERROR_CONNECT_SESSION_LOGIN_FAILED,
        DZ_ERROR_USER_PROFILE_PERM_DENIED,
        DZ_ERROR_CACHE_DIRECTORY_PERM_DENIED,
        DZ_ERROR_CONNECT_SESSION_NOT_ONLINE,
        DZ_ERROR_CONNECT_SESSION_OFFLINE_MODE,
        DZ_ERROR_CONNECT_NO_OFFLINE_CACHE
    ) = range(0x00010000, 0x00010007)

    (
        DZ_ERROR_CATEGORY_PLAYER,
        DZ_ERROR_PLAYER_QUEUELIST_NONE_SET,
        DZ_ERROR_PLAYER_QUEUELIST_BAD_INDEX,
        DZ_ERROR_PLAYER_QUEUELIST_NO_MEDIA,
        DZ_ERROR_PLAYER_QUEUELIST_NO_RIGHTS,
        DZ_ERROR_PLAYER_QUEUELIST_RIGHT_TIMEOUT,
        DZ_ERROR_PLAYER_QUEUELIST_RADIO_TOO_MANY_SKIP,
        DZ_ERROR_PLAYER_QUEUELIST_NO_MORE_TRACK,
        DZ_ERROR_PLAYER_PAUSE_NOT_STARTED,
        DZ_ERROR_PLAYER_PAUSE_ALREADY_PAUSED,
        DZ_ERROR_PLAYER_UNPAUSE_NOT_STARTED,
        DZ_ERROR_PLAYER_UNPAUSE_NOT_PAUSED,
        DZ_ERROR_PLAYER_SEEK_NOT_SEEKABLE_NOT_STARTED,
        DZ_ERROR_PLAYER_SEEK_NOT_SEEKABLE_NO_DURATION,
        DZ_ERROR_PLAYER_SEEK_NOT_SEEKABLE_NOT_INDEXED,
        DZ_ERROR_PLAYER_SEEK_NOT_SEEKABLE
    ) = range(0x00020000, 0x00020010)

    (
        DZ_ERROR_CATEGORY_MEDIASTREAMER,
        DZ_ERROR_MEDIASTREAMER_BAD_URL_SCHEME,
        DZ_ERROR_MEDIASTREAMER_BAD_URL_HOST,
        DZ_ERROR_MEDIASTREAMER_BAD_URL_TRACK,
        DZ_ERROR_MEDIASTREAMER_NOT_AVAILABLE_OFFLINE,
        DZ_ERROR_MEDIASTREAMER_NOT_READABLE,
        DZ_ERROR_MEDIASTREAMER_NO_DURATION,
        DZ_ERROR_MEDIASTREAMER_NOT_INDEXED,
        DZ_ERROR_MEDIASTREAMER_SEEK_NOT_SEEKABLE,
        DZ_ERROR_MEDIASTREAMER_NO_DATA,
        DZ_ERROR_MEDIASTREAMER_END_OF_STREAM,
        DZ_ERROR_MEDIASTREAMER_ALREADY_MAPPED,
        DZ_ERROR_MEDIASTREAMER_NOT_MAPPED
    ) = range(0x00030000, 0x0003000D)

    (
        DZ_ERROR_CATEGORY_OFFLINE,
        DZ_ERROR_OFFLINE_FS_FULL,
        DZ_ERROR_PLAYER_BAD_URL
    ) = range(0x00040000, 0x00040003)
